version: "3.8"

services:
  data-analysis-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o
    volumes:
      - ./recommand_place/data:/app/recommand_place/data
      - ./text_ai/my_best_model:/app/text_ai/my_best_model
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
